spring.application.name=restful-web-services


#spring.mvc.apiversion.use.path-segment=0
#spring.mvc.apiversion.use.query-parameter=version
#spring.mvc.apiversion.use.header=X-API-VERSION
#spring.mvc.apiversion.use.media-type-parameter[application/json]=version

# Expose all actuator endpoints
management.endpoints.web.exposure.include=*

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
